# Application Name
spring.application.name=imart-backend

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/imart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Spring Security Configuration
# ===============================
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# ===============================
# Server Configuration
# ===============================
server.port=8081
#server.servlet.context-path=/api

# ===============================
# Springdoc OpenAPI Configuration
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true

# ===============================
# Logging Configuration
# ===============================
logging.level.com.imart=DEBUG
logging.level.org.springframework.web=DEBUG

// jwt configration
jwt.secret=super-secret-key-123-iwanthadsfadjksfjaahdfarejraehriewjirdgjndfjdfjsfzkjafgajh
jwt.expiration=86400000
